Icon
emarkees/Hello-world pull request #2
Opened 2022-10-26 10:47 UTC by emarkees

Pulling a request

2022-10-26 13:40 UTC, Kamba56 requested changes
Hi @emarkees, 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.


 ## Highlights
- [x] Professional Readme

 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-10-26 13:40 UTC, Kamba56 commented on .github/workflows/linters.yml
> +name: Linters
- [ ] Please in the future, do not open a new pull request for a re-review. Always implement all the changes suggested by the code reviewer on the same branch and submit the same pull request for a re-review.

- [ ] As requested by the previous reviewer, kindly set up linters correctly. You can set up linters by copying the files in [this repo](https://github.com/microverseinc/linters-config/tree/master/html-css) to your repo and run `npm install --save-dev hint@7.x` in your terminal to install webhint and then run `npm install --save-dev stylelint@13.x stylelint-scss@3.x stylelint-config-standard@21.x stylelint-csstree-validator@1.x` to install stylelint.

2022-10-26 13:40 UTC, Kamba56 commented on .gitignore
> +
- [ ] As requested by the previous reviewer, kindly add node_modules to your .gitignore file. This is to prevent it from being pushed to your repo. The node_modules folder will be created locally once you install linters.

- [ ] As requested by the previous code reviewer, please edit your pull request title and description. Your PR title should be a description of changes implemented in the pull request and your PR description should be a summary of all the changes you implemented in the branch. This is to make your work more professional. Kindly go [here](https://github.com/microverseinc/curriculum-transversal-skills/blob/main/documentation/articles/professional_repo_rules.md) to read more about professional PR.

2022-10-26 13:40 UTC, Kamba56 commented on index.html
> +<html>
- [Optional] Consider adding a `<head>` element to your HTML. This is more semantically correct in HTML.
- [Optiona] Please in future projects, make sure that your branch name is a feature or action that is to be implemented in the branch. This is best practice for GitHub flow. A good branch name is `setup-hello-microverse`. Kindly check [here](https://github.com/microverseinc/curriculum-transversal-skills/blob/main/git-github/articles/github_flow.md#feature-branches) for more details.

2022-10-26 21:33 UTC, Kamba56 commented
@emarkees, please request for a re-review from your dashboard by submitting the link to the pull request.

2022-10-27 06:56 UTC, emarkees commented on .github/workflows/linters.yml
> +name: Linters
Changes have been made should i request for a new review

2022-10-27 07:18 UTC, 1GORDON approved these changes
# Status: APPROVED 🟢 

Hi @emarkees ✋

<img src="https://media.giphy.com/media/BPJmthQ3YRwD6QqcVD/giphy.gif" width="480" height="270" class="giphy-embed" />

Your project is complete!  There is nothing else to say other than... it's time to merge it: ship it:
Congratulations! :tada: :clap: :clap: :100:

## Highlights!
- Followed Gitflow ✔️ 
- Linters are passing ✔️
- Descriptive Pull request ✔️

## Optional suggestions

- [ ] You may always write your commit messages in an imperative tense something like `Add Linter Files` instead of `Adding Linter files`.
- [ ] You may add all the linter files to your repo including the `.hintrc` and `stylelintrc.json` files. You may find them in this [link](https://github.com/microverseinc/linters-config/tree/master/html-css).

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you consider them as they can improve your code._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread and tag me `@1GORDON` if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-10-27 07:18 UTC, 1GORDON commented on index.html
> +<h1>Hello Microverse!</h1>
Great job @emarkees 🤝

- [ ] [Optional] Kindly add a class to your HTML element and use this class to apply styles to your element in the stylesheet through this class.

2022-10-27 09:26 UTC, emarkees commented on index.html
> +<h1>Hello Microverse!</h1>
done @1GORDON

2022-10-27 19:25 UTC, merged